<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<!-- BEGIN GTAG GLOBAL TAG -->
<?php if ($id = $block->getGtagConfig()->getId()): ?>
    <script async src="https://www.googletagmanager.com/gtag/js?id=<?= /* @noEscape */ $id; ?>"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments)};
        gtag('js', new Date());
        gtag('config', '<?= /* @noEscape */ $id; ?>');
    </script>
<?php endif; ?>
<!-- END GTAG GLOBAL TAG -->
